#! /bin/bash

/bin/bash ../../build/aux/test-driver --test-name configfile-bom.sh --log-file configfile-bom.sh.log --trs-file configfile-bom.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-bom.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-error_logging-y1.sh --log-file configfile-error_logging-y1.sh.log --trs-file configfile-error_logging-y1.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-error_logging-y1.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-error_logging-y2.sh --log-file configfile-error_logging-y2.sh.log --trs-file configfile-error_logging-y2.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-error_logging-y2.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-error_logging-y3.sh --log-file configfile-error_logging-y3.sh.log --trs-file configfile-error_logging-y3.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-error_logging-y3.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-error_logging-n1.sh --log-file configfile-error_logging-n1.sh.log --trs-file configfile-error_logging-n1.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-error_logging-n1.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-error_logging-n2.sh --log-file configfile-error_logging-n2.sh.log --trs-file configfile-error_logging-n2.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-error_logging-n2.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-error_logging-n3.sh --log-file configfile-error_logging-n3.sh.log --trs-file configfile-error_logging-n3.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-error_logging-n3.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-inline-comment.sh --log-file configfile-inline-comment.sh.log --trs-file configfile-inline-comment.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-inline-comment.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-line-length-1023.sh --log-file configfile-line-length-1023.sh.log --trs-file configfile-line-length-1023.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-line-length-1023.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-line-length-1024.sh --log-file configfile-line-length-1024.sh.log --trs-file configfile-line-length-1024.sh.trs --color-tests no --enable-hard-errors yes --expect-failure yes -- ./configfile-line-length-1024.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-filter_chain-1.sh --log-file configfile-filter_chain-1.sh.log --trs-file configfile-filter_chain-1.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-filter_chain-1.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-message_format-1.sh --log-file configfile-message_format-1.sh.log --trs-file configfile-message_format-1.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-message_format-1.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-message_format-unquoted.sh --log-file configfile-message_format-unquoted.sh.log --trs-file configfile-message_format-unquoted.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-message_format-unquoted.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-message_format-single-quoted.sh --log-file configfile-message_format-single-quoted.sh.log --trs-file configfile-message_format-single-quoted.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-message_format-single-quoted.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-message_format-double-quoted.sh --log-file configfile-message_format-double-quoted.sh.log --trs-file configfile-message_format-double-quoted.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-message_format-double-quoted.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-output-devlog.sh --log-file configfile-output-devlog.sh.log --trs-file configfile-output-devlog.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-output-devlog.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-output-file.sh --log-file configfile-output-file.sh.log --trs-file configfile-output-file.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-output-file.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-output-invalid.sh --log-file configfile-output-invalid.sh.log --trs-file configfile-output-invalid.sh.trs --color-tests no --enable-hard-errors yes --expect-failure yes -- ./configfile-output-invalid.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-output-socket.sh --log-file configfile-output-socket.sh.log --trs-file configfile-output-socket.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-output-socket.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-syslog_facility.sh --log-file configfile-syslog_facility.sh.log --trs-file configfile-syslog_facility.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-syslog_facility.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-syslog_ident.sh --log-file configfile-syslog_ident.sh.log --trs-file configfile-syslog_ident.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-syslog_ident.sh
/bin/bash ../../build/aux/test-driver --test-name configfile-syslog_level.sh --log-file configfile-syslog_level.sh.log --trs-file configfile-syslog_level.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./configfile-syslog_level.sh
