CFLAGS = -pthread

all:
	make main.rs

main: a.o b.o
	$(CC) $(CFLAGS) -o $@ $^

main.c: a.c
	CC="cilly --gcc=/usr/bin/clang-14 --merge --keepmerged --noPrintLn" make main && \
	rm main *.o && \
	mv main_comb.c main.c

main.rs: main.c
	echo "[{\"arguments\":[\"cc\",\"-c\",\"-pthread\",\"-o\",\"main.o\",\"main.c\"],\"directory\":\"`pwd`\",\"file\":\"main.c\"}]" > compile_commands.json && \
	rm -f main.rs && \
	c2rust transpile -e compile_commands.json && \
	cargo fmt

clean:
	rm -rf main main.c *.o *.xml compile_commands.json *.rs *.rlib Cargo.* rust-toolchain target
