#! /bin/bash

/bin/bash ../../build/aux/test-driver --test-name filter_exclude_spawns_of-mustdrop-multiarg-first.sh --log-file filter_exclude_spawns_of-mustdrop-multiarg-first.sh.log --trs-file filter_exclude_spawns_of-mustdrop-multiarg-first.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_exclude_spawns_of-mustdrop-multiarg-first.sh
/bin/bash ../../build/aux/test-driver --test-name filter_exclude_spawns_of-mustdrop-multiarg-last.sh --log-file filter_exclude_spawns_of-mustdrop-multiarg-last.sh.log --trs-file filter_exclude_spawns_of-mustdrop-multiarg-last.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_exclude_spawns_of-mustdrop-multiarg-last.sh
/bin/bash ../../build/aux/test-driver --test-name filter_exclude_spawns_of-mustdrop-multiarg-mid.sh --log-file filter_exclude_spawns_of-mustdrop-multiarg-mid.sh.log --trs-file filter_exclude_spawns_of-mustdrop-multiarg-mid.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_exclude_spawns_of-mustdrop-multiarg-mid.sh
/bin/bash ../../build/aux/test-driver --test-name filter_exclude_spawns_of-mustdrop-singlearg.sh --log-file filter_exclude_spawns_of-mustdrop-singlearg.sh.log --trs-file filter_exclude_spawns_of-mustdrop-singlearg.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_exclude_spawns_of-mustdrop-singlearg.sh
/bin/bash ../../build/aux/test-driver --test-name filter_exclude_spawns_of-mustdrop-spaceparent.sh --log-file filter_exclude_spawns_of-mustdrop-spaceparent.sh.log --trs-file filter_exclude_spawns_of-mustdrop-spaceparent.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_exclude_spawns_of-mustdrop-spaceparent.sh
/bin/bash ../../build/aux/test-driver --test-name filter_exclude_spawns_of-mustlog-multiarg.sh --log-file filter_exclude_spawns_of-mustlog-multiarg.sh.log --trs-file filter_exclude_spawns_of-mustlog-multiarg.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_exclude_spawns_of-mustlog-multiarg.sh
/bin/bash ../../build/aux/test-driver --test-name filter_exclude_spawns_of-mustlog-singlearg.sh --log-file filter_exclude_spawns_of-mustlog-singlearg.sh.log --trs-file filter_exclude_spawns_of-mustlog-singlearg.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_exclude_spawns_of-mustlog-singlearg.sh
/bin/bash ../../build/aux/test-driver --test-name filter_exclude_spawns_of-mustlog-spaceparent.sh --log-file filter_exclude_spawns_of-mustlog-spaceparent.sh.log --trs-file filter_exclude_spawns_of-mustlog-spaceparent.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_exclude_spawns_of-mustlog-spaceparent.sh
/bin/bash ../../build/aux/test-driver --test-name filter_exclude_uid-pass.sh --log-file filter_exclude_uid-pass.sh.log --trs-file filter_exclude_uid-pass.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_exclude_uid-pass.sh
/bin/bash ../../build/aux/test-driver --test-name filter_exclude_uid-pass-multi.sh --log-file filter_exclude_uid-pass-multi.sh.log --trs-file filter_exclude_uid-pass-multi.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_exclude_uid-pass-multi.sh
/bin/bash ../../build/aux/test-driver --test-name filter_exclude_uid-drop.sh --log-file filter_exclude_uid-drop.sh.log --trs-file filter_exclude_uid-drop.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_exclude_uid-drop.sh
/bin/bash ../../build/aux/test-driver --test-name filter_exclude_uid-drop-multi.sh --log-file filter_exclude_uid-drop-multi.sh.log --trs-file filter_exclude_uid-drop-multi.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_exclude_uid-drop-multi.sh
/bin/bash ../../build/aux/test-driver --test-name filter_only_tty.sh --log-file filter_only_tty.sh.log --trs-file filter_only_tty.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_only_tty.sh
/bin/bash ../../build/aux/test-driver --test-name filter_only_uid-pass.sh --log-file filter_only_uid-pass.sh.log --trs-file filter_only_uid-pass.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_only_uid-pass.sh
/bin/bash ../../build/aux/test-driver --test-name filter_only_uid-pass-multi.sh --log-file filter_only_uid-pass-multi.sh.log --trs-file filter_only_uid-pass-multi.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_only_uid-pass-multi.sh
/bin/bash ../../build/aux/test-driver --test-name filter_only_uid-drop.sh --log-file filter_only_uid-drop.sh.log --trs-file filter_only_uid-drop.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_only_uid-drop.sh
/bin/bash ../../build/aux/test-driver --test-name filter_only_uid-drop-multi.sh --log-file filter_only_uid-drop-multi.sh.log --trs-file filter_only_uid-drop-multi.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filter_only_uid-drop-multi.sh
/bin/bash ../../build/aux/test-driver --test-name filterchain-drop.sh --log-file filterchain-drop.sh.log --trs-file filterchain-drop.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filterchain-drop.sh
/bin/bash ../../build/aux/test-driver --test-name filterchain-pass.sh --log-file filterchain-pass.sh.log --trs-file filterchain-pass.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filterchain-pass.sh
/bin/bash ../../build/aux/test-driver --test-name filterchain-unknown-filter.sh --log-file filterchain-unknown-filter.sh.log --trs-file filterchain-unknown-filter.sh.trs --color-tests no --enable-hard-errors yes --expect-failure no -- ./filterchain-unknown-filter.sh
