CFLAGS = -pthread

all:
	make a.xml main.rs clean-intermediate

a.xml: main.c
	goblint --conf ../../conf.json \
		--enable allglobs \
		--set result fast_xml \
		--set outfile a.xml \
		main.c

compile_commands.json:
	echo "[{\"arguments\":[\"cc\",\"-c\",\"-pthread\",\"-o\",\"main.o\",\"main.c\"],\"directory\":\"`pwd`\",\"file\":\"main.c\"}]" > compile_commands.json

main.rs: compile_commands.json
	c2rust transpile -e compile_commands.json && \
	cargo fmt

clean:
	rm -rf *.xml *.json *.rs Cargo.* rust-toolchain target

clean-intermediate:
	rm -rf *.json Cargo.lock target
