CFLAGS = -pthread

all:
	make a.json

a.xml: main.c conf.json
	goblint --conf conf.json \
		--enable allglobs \
		--set result fast_xml \
		--set outfile a.xml \
		main.c

main.rs: main.c
	echo "[{\"arguments\":[\"cc\",\"-c\",\"-pthread\",\"-o\",\"main.o\",\"main.c\"],\"directory\":\"`pwd`\",\"file\":\"main.c\"}]" > compile_commands.json && \
	rm -f main.rs && \
	c2rust transpile -e compile_commands.json && \
	cargo fmt

ifeq ($(GOBLINT),yes)
CMD = goblint2json
else
CMD = dataflow
endif

a.json: a.xml main.rs
	cargo run --release --manifest-path ../../Cargo.toml --bin ${CMD} -- -i . -d ../../deps

clean:
	rm -rf *.xml a.json compile_commands.json *.rs Cargo.* rust-toolchain target *.rlib
