CFLAGS = -pthread

main.rs: main.c
	echo "[{\"arguments\":[\"cc\",\"-c\",\"-pthread\",\"-o\",\"main.o\",\"main.c\"],\"directory\":\"`pwd`\",\"file\":\"main.c\"}]" > compile_commands.json && \
	rm -f main.rs && \
	c2rust transpile -e compile_commands.json > lines && \
	if [ -f "fix_rust_code.sh" ]; then ./fix_rust_code.sh; fi

ifeq ($(LIB),yes)
FLAG = --enable allfuns --enable exp.earlyglobs
endif

a.xml: main.c
	goblint --conf ../../conf.json $(FLAG) \
		--enable allglobs \
		--enable justcfg \
		--set result fast_xml \
		--set outfile a.xml \
		main.c

clean:
	rm -rf *.xml a.json compile_commands.json *.rs Cargo.* rust-toolchain target *.rlib *.dot lines
